// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dm_bot.Contexts;

namespace dm_bot.Migrations
{
    [DbContext(typeof(DMContext))]
    [Migration("20190317202749_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("dm_bot.Models.DungeonMasterAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChatCommChannel");

                    b.Property<string>("ChronusTimeLink");

                    b.Property<int>("CombatPercent");

                    b.Property<string>("DungeonMasterUserName");

                    b.Property<int>("MaxHours");

                    b.Property<int>("MinHours");

                    b.Property<DateTime>("PlayDate");

                    b.Property<int>("RoleplayingPercent");

                    b.Property<string>("VoiceCommChannel");

                    b.HasKey("Id");

                    b.ToTable("DungeonMasterAvailabilities");
                });

            modelBuilder.Entity("dm_bot.Models.InventoryItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ItemId");

                    b.Property<int?>("PlayerId");

                    b.Property<int>("Quantity");

                    b.HasKey("ID");

                    b.HasIndex("ItemId");

                    b.HasIndex("PlayerId");

                    b.ToTable("InventoryItem");
                });

            modelBuilder.Entity("dm_bot.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("CopperCost");

                    b.Property<decimal>("ElectrumCost");

                    b.Property<decimal>("GoldCost");

                    b.Property<bool>("IsTradeOnly");

                    b.Property<string>("Name");

                    b.Property<decimal>("SellValue");

                    b.Property<decimal>("SilverCost");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("dm_bot.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Description");

                    b.Property<int>("Difficulty");

                    b.Property<int?>("DungeonMasterAvailabilityId");

                    b.Property<string>("JobLink");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("DungeonMasterAvailabilityId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("dm_bot.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CharacterName");

                    b.Property<decimal>("Copper");

                    b.Property<string>("DiscordMention");

                    b.Property<decimal>("Electrum");

                    b.Property<decimal>("Gold");

                    b.Property<string>("RoleIds");

                    b.Property<decimal>("Silver");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("dm_bot.Models.Rank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DungeonMasterAvailabilityId");

                    b.Property<string>("RankLetter");

                    b.Property<string>("RankName");

                    b.HasKey("Id");

                    b.HasIndex("DungeonMasterAvailabilityId");

                    b.ToTable("Ranks");
                });

            modelBuilder.Entity("dm_bot.Models.InventoryItem", b =>
                {
                    b.HasOne("dm_bot.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("dm_bot.Models.Player")
                        .WithMany("PlayerInventory")
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("dm_bot.Models.Job", b =>
                {
                    b.HasOne("dm_bot.Models.DungeonMasterAvailability")
                        .WithMany("Jobs")
                        .HasForeignKey("DungeonMasterAvailabilityId");
                });

            modelBuilder.Entity("dm_bot.Models.Rank", b =>
                {
                    b.HasOne("dm_bot.Models.DungeonMasterAvailability")
                        .WithMany("TaggedRanks")
                        .HasForeignKey("DungeonMasterAvailabilityId");
                });
#pragma warning restore 612, 618
        }
    }
}
